### ISSUE TITLE
Some questions about ‘experiments.py’ and the dataset

### ISSUE THREAD

**Issue by ZoeLee0220** [jpfolch/MFBoom#1]
@jpfolch  Hello, I am a beginner in parallel optimization. Your approach is very efficient and creative, but I have encountered some issues while learning:

1. In 'experiments.py', does alpha (battery_alpha) represent the evaluation function of the battery, i.e., the model obtained through 'battery_func.py'?
2. 
3. If my understanding of the previous question is correct, the pseudocode 'Obtain observations Yt from queries Xt, with index set It' confuses me. Why not use this expensive model (if available, or real experiments) to evaluate the sampled points, instead of using a sequence search? How to handle the case when the sampled points are not included in the sequence?

Thank you.

**Comment by jpfolch** [comment]
Hello! 

 1. In 'experiments.py' the battery_alpha represents how close the lower fidelity is to the high fidelity. We take two samples of the GP and define:
  
 $h(x) = f_1(x)$
 $l(x) = \alpha f_1(x) + (1 - \alpha) f_2(x)$
  
 where $h$ is the high fidelity, and $l$ is the low fidelity. This allowed us to control how informative the lower fidelity is of the high fidelity. In the paper we ended up using $\alpha = 0$ or something very small.

2. Sorry, I cannot see the second question.

3. We obtain observations at time $t$, $Y_t$, and they correspond to queries $X_t$. The index set corresponds to the fidelity of each of those observations. The model we train uses observations from all fidelities at the same time.

**Comment by ZoeLee0220** [comment]
Thank you for your patience.
